#ifndef _MOTOR_CONFIG_H
#define _MOTOR_CONFIG_H

#include <string.h>
#include <stdint.h>
#include "stm32f4xx_hal_conf.h"

#include "can.h"

// 电机接收配置(注意不会影响发送)

#if ROBOT == CHEN_JING_YUAN

// pitch 电机
#define PITCH_MOTOR_CAN_ID 0x207 // pitch轴ID
#define PITCH_MOTOR_CAN CAN2

// 摩擦轮电机
#define LEFT_FRICTION_WHEEL_CAN_ID 0x201  // 摩擦轮ID1(左)
#define RIGHT_FRICTION_WHEEL_CAN_ID 0x202 // 摩擦轮ID2(右)
#define FRICTION_WHEEL_CAN CAN2

// Yaw轴电机
#define YAW_MOTOR_CAN_ID 0x205 // yaw轴电机
#define YAW_MOTOR_CAN CAN1

// 拨弹电机
#define TOGGLE_MOTOR_CAN_ID 0x204 // 拨弹电机
#define TOGGLE_MOTOR_CAN CAN1

// 底盘通信
#define SEND_TO_CHASSIS_CAN_ID_1 0x150
#define SEND_TO_CHASSIS_CAN_ID_2 0x151
#define GET_FROM_CHASSIS_CAN_ID_1 0x160
#define GET_FROM_CHASSIS_CAN_ID_2 0x161
#define CHASSIS_CAN_COMM_CAN_Handlerx hcan1
#define CHASSIS_CAN_COMM_CANx CAN1

// FIFO 0 接收ID
#define CAN1_FIFO0_ID0 0x000
#define CAN1_FIFO0_ID1 0x001
#define CAN1_FIFO0_ID2 TOGGLE_MOTOR_CAN_ID
#define CAN1_FIFO0_ID3 YAW_MOTOR_CAN_ID

// FIFO 1 接收ID
#define CAN1_FIFO1_ID0 GET_FROM_CHASSIS_CAN_ID_2
#define CAN1_FIFO1_ID1 GET_FROM_CHASSIS_CAN_ID_1
#define CAN1_FIFO1_ID2 0x002
#define CAN1_FIFO1_ID3 0x003

// FIFO 0 接收ID
#define CAN2_FIFO0_ID0 0x001
#define CAN2_FIFO0_ID1 PITCH_MOTOR_CAN_ID
#define CAN2_FIFO0_ID2 0x004
#define CAN2_FIFO0_ID3 0x000

// FIFO 1 接收ID
#define CAN2_FIFO1_ID0 0x003
#define CAN2_FIFO1_ID1 LEFT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID2 RIGHT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID3 0x000

#elif ROBOT == NIU_MO_SON

// pitch 电机
#define PITCH_MOTOR_CAN_ID 0x207 // pitch轴ID
#define PITCH_MOTOR_CAN CAN2

// 摩擦轮电机
#define LEFT_FRICTION_WHEEL_CAN_ID 0x201  // 摩擦轮ID1(左)
#define RIGHT_FRICTION_WHEEL_CAN_ID 0x202 // 摩擦轮ID2(右)
#define FRICTION_WHEEL_CAN CAN2

// Yaw轴电机
#define YAW_MOTOR_CAN_ID 0x205 // yaw轴电机
#define YAW_MOTOR_CAN CAN1

// 拨弹电机
#define TOGGLE_MOTOR_CAN_ID 0x204 // 拨弹电机
#define TOGGLE_MOTOR_CAN CAN1

// 底盘通信
#define SEND_TO_CHASSIS_CAN_ID_1 0x150
#define SEND_TO_CHASSIS_CAN_ID_2 0x151
#define GET_FROM_CHASSIS_CAN_ID_1 0x160
#define GET_FROM_CHASSIS_CAN_ID_2 0x161
#define CHASSIS_CAN_COMM_CANx CAN1

// FIFO 0 接收ID
#define CAN1_FIFO0_ID0 0x000
#define CAN1_FIFO0_ID1 0x001
#define CAN1_FIFO0_ID2 TOGGLE_MOTOR_CAN_ID
#define CAN1_FIFO0_ID3 YAW_MOTOR_CAN_ID

// FIFO 1 接收ID
#define CAN1_FIFO1_ID0 GET_FROM_CHASSIS_CAN_ID_2
#define CAN1_FIFO1_ID1 GET_FROM_CHASSIS_CAN_ID_1
#define CAN1_FIFO1_ID2 0x002
#define CAN1_FIFO1_ID3 0x003

// FIFO 0 接收ID
#define CAN2_FIFO0_ID0 0x001
#define CAN2_FIFO0_ID1 PITCH_MOTOR_CAN_ID
#define CAN2_FIFO0_ID2 0x004
#define CAN2_FIFO0_ID3 0x000

// FIFO 1 接收ID
#define CAN2_FIFO1_ID0 0x003
#define CAN2_FIFO1_ID1 LEFT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID2 RIGHT_FRICTION_WHEEL_CAN_ID
#define CAN2_FIFO1_ID3 0x000
#endif

#endif // !_MOTOR_CONFIG_H
